# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8550-modules/motorola/include

prod_list := devon
find_target := $(foreach find, $(prod_list), $(findstring $(find), $(TARGET_PRODUCT)))
find_target := $(strip $(find_target))
$(warning find_target=$(find_target))
ifneq ($(find_target),)
$(warning define SUPPORT_PIN_CTRL)
EXTRA_CFLAGS += -DSUPPORT_PIN_CTRL
endif

# if building as external module, Kconfig options defined
# externally are ignored when making the final .config file
# and this driver doesn't even have a Kconfig,
# so set some defaults here:
ifeq ($(CONFIG_ARCH_KHAJE), y)
        CONFIG_INPUT_MISC_FPC1020_SAVE_TO_CLASS_DEVICE=y
endif

ifneq ($(filter m y,$(CONFIG_INPUT_MISC_FPC1020_SAVE_TO_CLASS_DEVICE)),)
	EXTRA_CFLAGS += -DCONFIG_INPUT_MISC_FPC1020_SAVE_TO_CLASS_DEVICE
endif

fpc1020_mmi-y += fpc1020_tee.o

obj-m += fpc1020_mmi.o

